apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
        labels:
          app: sample
    spec:
      serviceAccountName: sample-acc
      containers:
      - name: bash
        image: bash:4.4.19
        volumeMounts:
        - name: shared-volume
          mountPath: /sidecar/
        command: ["watch"]
        args: ["ls", "/sidecar/"]
      - name: sidecar
        image: ananace/k8s-sidecar:latest
        volumeMounts:
        - name: shared-volume
          mountPath: /sidecar/
        env:
        - name: LABEL
          value: "com.github.ananace/FindMe"
        - name: FOLDER
          value: /sidecar/
      - name: concat-sidecar
        image: ananace/k8s-sidecar:latest
        volumeMounts:
        - name: shared-volume
          mountPath: /sidecar/
        env:
        - name: LABEL
          value: "com.github.ananace/FindMe"
        - name: FOLDER
          value: /sidecar/
        - name: CONCAT
          value: concatenated.ini
        - name: CONCAT_HEADER
          value: '#'
      volumes:
      - name: shared-volume
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  labels:
    com.github.ananace/FindMe: ""
data:
  hello.world: |-
     Hello World!
  goodbye.world: |-
     Goodbye World!
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-acc
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample-rolebind
roleRef:
  kind: ClusterRole
  name: sample-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sample-acc
  namespace: default
